language: node_js
sudo: required

services:
  - docker

before_script:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker build -t vitabot .

script:
  - docker run vitabot eslint . --ext .js .dbj